name: multimods3
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - av
  - cuda-compiler  # Necessary for `torch.compile()` to work
  - numpy
  - opencv
  - pandas
  - pillow
  - pyyaml
  - scikit-image
  - pytorch-gpu>=2.6
  - torchcodec>=0.3
  - torchvision
  - tqdm
  - pip